---
# Install Oracle Java 8

# Installing via http://www.webupd8.org/2012/09/install-oracle-java-8-in-ubuntu-via-ppa.html
- name: Update cert and repositories
  apt: pkg=ca-certificates state=latest update_cache=yes

- name: Install python-software-properties
  apt: pkg=python-software-properties state=latest

- name: Adding Java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: Auto accepting Java license
  shell: echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | sudo /usr/bin/debconf-set-selections
  
- name: Installing Oracle Java 8 and support libs
  apt: pkg=oracle-java8-installer state=latest install_recommends=yes
